SyntaxError
error running storybook out of the box

```
/Users/phoenixbox/Dev/openSource/formik/.storybook/webpack.config.js:12
  )
  ^
SyntaxError: Unexpected token )
    at Object.exports.runInThisContext (vm.js:78:16)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at exports.default (/Users/phoenixbox/Dev/openSource/formik/node_modules/@storybook/react/dist/server/config.js:57:22)
    at exports.default (/Users/phoenixbox/Dev/openSource/formik/node_modules/@storybook/core/dist/server/middleware.js:19:16)
    at buildDev (/Users/phoenixbox/Dev/openSource/formik/node_modules/@storybook/core/dist/server/build-dev.js:163:36)
    at Object.<anonymous> (/Users/phoenixbox/Dev/openSource/formik/node_modules/@storybook/react/dist/server/index.js:23:22)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
```